### ISSUE TITLE
Error: Can't find stylesheet to import (@awsui/design-tokens/index.scss)

### ISSUE THREAD

**Issue by mwbouwkamp-mendix** [awslabs/iot-app-kit#1945]
**Describe the bug**
In a Mendix widget that implements the iot-app-kit, when I update from 5.7.0 to 7.3.1, I get an error during building my react widget for file `@iot-app-kit\scene-composer\dist\src\layouts\SceneLayout\components\FoldableContainer.scss` saying:

Error: Can't find stylesheet to import.

Any idea what is the problem here? Are there breaking changes?

Output:
[!] (plugin postcss) Error: Can't find stylesheet to import.
  ╷
1 │ @use '@awsui/design-tokens/index.scss' as awsui;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@iot-app-kit\scene-composer\dist\src\layouts\SceneLayout\components\FoldableContainer.scss 1:1  root stylesheet
node_modules/@iot-app-kit/scene-composer/dist/src/layouts/SceneLayout/components/FoldableContainer.scss
Error: Can't find stylesheet to import.
  ╷
1 │ @use '@awsui/design-tokens/index.scss' as awsui;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@iot-app-kit\scene-composer\dist\src\layouts\SceneLayout\components\FoldableContainer.scss 1:1  root stylesheet
    at Object.wrapException (...\node_modules\sass\sass.dart.js:1247:17)
    at NodeImporter._handleImportResult$4 (...\node_modules\sass\sass.dart.js:85828:17)
    at ...\node_modules\sass\sass.dart.js:85750:50
    at _wrapJsFunctionForAsync_closure.$protected (...\node_modules\sass\sass.dart.js:3738:15)
    at _wrapJsFunctionForAsync_closure.call$2 (...\node_modules\sass\sass.dart.js:28402:12)
    at _awaitOnObject_closure.call$1 (...\node_modules\sass\sass.dart.js:28390:32)
    at Object._rootRunUnary (...\node_modules\sass\sass.dart.js:4113:18)
    at StaticClosure.<anonymous> (...\node_modules\sass\sass.dart.js:99102:16)
    at _CustomZone.runUnary$2$2 (...\node_modules\sass\sass.dart.js:29799:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (...\node_modules\sass\sass.dart.js:28871:51)

**Comment by mwbouwkamp-mendix** [comment]
Trying it for the third time from scratch somehow fixed it...

**Comment by mwbouwkamp-mendix** [comment]
To be more precise, the issue seems to be with @iot-app-kit/scene-composer

**Comment by mitchlee-amzn** [comment]
In the most recent versions of AppKit, we no longer depend on @awsui packages, and have declared @cloudscape dependencies as peer, which you will install yourself to resolve this issue.
